// AUTO-GENERATED by scripts/proof-facts.mjs. Do not edit.
// Regenerated by the hypr-tiling-web prebuild from packages/hypr-tiling.

export interface ProofFacts {
  readonly version: string;
  readonly testSuites: number;
  readonly tests: number;
  readonly gzipIndexBytes: number;
  readonly gzipEngineBytes: number;
  readonly runtimeDependencyCount: number;
  readonly runtimeDependencies: ReadonlyArray<string>;
  readonly reactPeer: string;
  readonly reactDomPeer: string;
  readonly license: string;
}

export const PROOF_FACTS: ProofFacts = {
  version: "26.9.9",
  testSuites: 66,
  tests: 1366,
  gzipIndexBytes: 7089,
  gzipEngineBytes: 30515,
  runtimeDependencyCount: 2,
  runtimeDependencies: [
    "clsx",
    "tailwind-merge",
  ],
  reactPeer: "^19",
  reactDomPeer: "^19",
  license: "LicenseRef-PolyForm-Perimeter-1.0.1",
};
